<script setup lang="ts">
import { computed, ref } from "vue";
import { LoaderCircle, MoreHorizontal } from "@lucide/vue";
import { toast } from "vue-sonner";
import type { StaffBranchAssignmentResponseDto } from "@/api/generated/models";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuSeparator, DropdownMenuTrigger } from "@/components/ui/dropdown-menu";
import { ScrollArea } from "@/components/ui/scroll-area";
import { activateStaffAssignment, deactivateStaffAssignment, removeStaffAssignment, setStaffPrimary } from "../api/staff-api";
import { staffErrorMessage } from "../utils/staff-error-messages";

type Action = "activate" | "deactivate" | "remove" | "primary";
const props = defineProps<{ staffId: string; assignment: StaffBranchAssignmentResponseDto; assignments: StaffBranchAssignmentResponseDto[] }>();
const emit = defineEmits<{ changed: [] }>();
const open = ref(false); const action = ref<Action>("activate"); const replacementBranchId = ref(""); const error = ref(""); const submitting = ref(false);
const replacements = computed(() => props.assignments.filter((item) => item.branchId !== props.assignment.branchId && item.isActive && item.branch.isActive));
const requiresReplacement = computed(() => props.assignment.isPrimary && ["deactivate", "remove"].includes(action.value) && replacements.value.length > 0);
const title = computed(() => ({ activate: "Kích hoạt phân công", deactivate: "Ngừng làm việc tại chi nhánh", remove: "Gỡ khỏi chi nhánh", primary: "Đặt làm chi nhánh chính" })[action.value]);
function begin(next: Action): void { action.value = next; replacementBranchId.value = ""; error.value = ""; open.value = true; }
async function submit(): Promise<void> { if (submitting.value) return; if (requiresReplacement.value && !replacementBranchId.value) { error.value = "Vui lòng chọn chi nhánh chính thay thế."; return; } submitting.value = true; try { const payload = replacementBranchId.value ? { replacementBranchId: replacementBranchId.value } : {}; if (action.value === "activate") await activateStaffAssignment(props.staffId, props.assignment.branchId); else if (action.value === "deactivate") await deactivateStaffAssignment(props.staffId, props.assignment.branchId, payload); else if (action.value === "primary") await setStaffPrimary(props.staffId, props.assignment.branchId); else { const result = await removeStaffAssignment(props.staffId, props.assignment.branchId, payload); toast.success(result.data.count === 0 ? "Phân công không còn tồn tại; dữ liệu đã được đồng bộ." : "Đã gỡ phân công khỏi chi nhánh."); open.value = false; emit("changed"); return; } toast.success(action.value === "activate" ? "Đã kích hoạt phân công; trạng thái tài khoản không tự thay đổi." : action.value === "deactivate" ? "Đã ngừng phân công tại chi nhánh." : "Đã cập nhật chi nhánh chính."); open.value = false; emit("changed"); } catch (cause) { toast.error(staffErrorMessage(cause)); emit("changed"); } finally { submitting.value = false; } }
</script>

<template><DropdownMenu><DropdownMenuTrigger as-child><Button type="button" size="icon" variant="ghost" aria-label="Mở thao tác phân công"><MoreHorizontal class="size-4"/></Button></DropdownMenuTrigger><DropdownMenuContent align="end" class="z-[60] w-60"><DropdownMenuItem v-if="!assignment.isActive && assignment.branch.isActive" @select="begin('activate')">Kích hoạt lại</DropdownMenuItem><DropdownMenuItem v-if="assignment.isActive && !assignment.isPrimary" @select="begin('primary')">Đặt làm chi nhánh chính</DropdownMenuItem><DropdownMenuItem v-if="assignment.isActive" @select="begin('deactivate')">Ngừng hoạt động</DropdownMenuItem><DropdownMenuSeparator/><DropdownMenuItem class="text-destructive focus:text-destructive" @select="begin('remove')">Gỡ khỏi chi nhánh</DropdownMenuItem></DropdownMenuContent></DropdownMenu>
  <Dialog :open="open" @update:open="(value) => !submitting && (open = value)"><DialogContent class="grid max-h-[90dvh] w-[calc(100vw-2rem)] grid-rows-[auto_minmax(0,1fr)_auto] overflow-hidden p-0 sm:max-w-lg"><DialogHeader class="border-b px-5 pb-4 pt-5 sm:px-6"><DialogTitle>{{ title }}</DialogTitle><DialogDescription>{{ assignment.branch.name }}</DialogDescription></DialogHeader><ScrollArea class="min-h-0 px-5 sm:px-6"><div class="space-y-4 py-5 text-sm"><p v-if="action === 'activate'">Kích hoạt phân công không tự kích hoạt tài khoản và không tự đặt chi nhánh chính.</p><p v-else-if="action === 'primary'">Chi nhánh này trở thành chi nhánh chính; tài khoản và trạng thái phân công không bị kích hoạt ngầm.</p><p v-else-if="action === 'remove'">Gỡ phân công sẽ xóa vai trò và quyền cấp trực tiếp của phân công, nhưng không xóa tài khoản người dùng.</p><p v-else>Phân công sẽ ngừng hoạt động. Nếu đây là phân công hoạt động cuối cùng, tài khoản bị khóa và các phiên đang hoạt động bị thu hồi theo quy tắc phía máy chủ.</p><section v-if="requiresReplacement" class="space-y-2"><p class="font-medium">Chi nhánh chính thay thế</p><button v-for="item in replacements" :key="item.id" type="button" class="w-full rounded-md border p-3 text-left" :class="replacementBranchId === item.branchId ? 'border-primary bg-primary/5' : ''" @click="replacementBranchId = item.branchId; error = ''">{{ item.branch.name }}</button><p v-if="error" role="alert" class="text-destructive">{{ error }}</p></section><p v-else-if="assignment.isPrimary && ['deactivate','remove'].includes(action)" class="rounded-md border border-amber-300 bg-amber-50 p-3 text-amber-900">Không có chi nhánh hoạt động phù hợp để thay thế. Tài khoản có thể bị khóa sau thao tác.</p></div></ScrollArea><DialogFooter class="border-t px-5 py-4 sm:px-6"><Button type="button" variant="outline" :disabled="submitting" @click="open = false">Hủy</Button><Button type="button" :variant="['remove','deactivate'].includes(action) ? 'destructive' : 'default'" :disabled="submitting" @click="submit"><LoaderCircle v-if="submitting" class="mr-2 size-4 animate-spin"/>Xác nhận</Button></DialogFooter></DialogContent></Dialog>
</template>
