export const ADMIN_PERMISSIONS = {
  DASHBOARD_READ: "dashboard.read",
  USERS_READ: "users.read",
  USERS_CREATE: "users.create",
  USERS_UPDATE: "users.update",
  USERS_DELETE: "users.delete",
  STAFF_READ: "staff.read",
  STAFF_CREATE: "staff.create",
  STAFF_ASSIGN_ROLE: "staff.assign_role",
  STAFF_ASSIGN_PERMISSION: "staff.assign_permission",
  STAFF_ASSIGN_BRANCH: "staff.assign_branch",
  BRANCH_ADMIN_ASSIGN: "branch_admin.assign",
  BRANCHES_READ: "branches.read",
  BRANCHES_CREATE: "branches.create",
  BRANCHES_UPDATE: "branches.update",
  BRANCHES_DELETE: "branches.delete",
  BRANCHES_ASSIGN: "branches.assign",
  ROLES_READ: "roles.read",
  ROLES_CREATE: "roles.create",
  ROLES_UPDATE: "roles.update",
  ROLES_DELETE: "roles.delete",
  ROLES_ASSIGN_PERMISSION: "roles.assign_permission",
  PERMISSIONS_READ: "permissions.read",
  PERMISSIONS_CREATE: "permissions.create",
  PERMISSIONS_UPDATE: "permissions.update",
  PERMISSIONS_DELETE: "permissions.delete",
  PRODUCTS_READ: "products.read",
  CATEGORIES_READ: "categories.read",
  CATEGORIES_CREATE: "categories.create",
  CATEGORIES_UPDATE: "categories.update",
  CATEGORIES_DELETE: "categories.delete",
  INVENTORY_READ: "inventory.read",
  STOCK_MOVEMENTS_READ: "stock_movements.read",
  ORDERS_READ: "orders.read",
  PAYMENTS_CREATE: "payments.create",
} as const;

export type AdminPermission =
  (typeof ADMIN_PERMISSIONS)[keyof typeof ADMIN_PERMISSIONS];
